{% set version = '0.4-17' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proxy
  version: {{ version|replace("-", "_") }}

source:
  fn: proxy_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/proxy_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/proxy/proxy_{{ version }}.tar.gz
  sha256: 82fe788b216651c26bfea0e9dea717554f42c47e831d6a2be448666c9275e12d

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('proxy')"  # [not win]
    - "\"%R%\" -e \"library('proxy')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=proxy
  license: GPL-2
  summary: 'Provides an extensible framework for the efficient calculation of auto- and cross-proximities,
    along with implementations of the most popular ones. '
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
