travis:
  secure:
    BINSTAR_TOKEN: riUyNzFNIMkw2xomafqPoKVunAp2oOJToV90vF/P8SCozvQBKnppTT0KUuAoWPHMfWkDWulDR/7JDu5bAinDL5KtfympZUwfvZtvOZgci3dr2P8Gb8ZA10qpUkN7wFE9bZw8NHRDsUW54lPMZUryPWbceAmjgzZjClRvW9j6gLx+0RGrN57VulR39n6ZI5knG+si0KCQwtDOWoN3T0I/PV43QSnEqlyI5AqVi0uwEHOZac1kDjT5Ki6QCVBNQHQ3TAc9oUtnYVscKNIgJF0wSAonLv1BKpeL3J32ggigepxzIkCyOuoxX6jHG1v+SFV4PaPQz3wWDHoblwR7G6Sfft4oUpPh5oq86WspvoBXYlPqPO306NPvHP3GkpfDsjzoB3xEUuvNts9zRp4N+JWVUWQ37K9MDVpic3r9rnwPj5RxPiCUnET3y0SffY9Dbp2eB/oJjHByzM59O3YcHZvTXn8ER2f9IuazcSr6/zk05kXUBwHoYvnFsRGV0WUEMsE/0e2l4zl6TxBpoNlCKNxI6mNVUbMWKWJ3fB1iSyJcy947gDmqs1y05KM3sun5Pr7dN9imQevnpQRollDe2e3RFUwLXmmVASUfjFm1Gb8L3jssU3D3pjcal1+cYl/puEdxj/wx2Fh5zp7mZDd9BKeY5ZxE5yLa6VQNjLEvS8UVVKs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
